import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbarr from './Components/Navbarr'
import Navbar from './Components/Navbar'
import FooterNavbar from './Components/FooterNavberr'
import Footer from './Components/Footer'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-white">
           
           <Navbarr />
           <Navbar />
           <main className="flex-grow">
             {children}
           </main>
           <FooterNavbar />
           <Footer />
       
     

      </body>
    </html>
  )
}
